### ISSUE TITLE
erorr working

### ISSUE THREAD

**Issue by AbdalaMask** [losttech/YOLOv4#1]
: 'None of discovered matching Python environments have TensorFlow 1.* installed. Please, install tensorflow or tensorflow-gpu 1.15.*, or use GradientEngine to configure Python home to use a different environment.

**Comment by AbdalaMask** [comment]
![image](https://user-images.githubusercontent.com/37013638/199315472-6374adec-a6b4-412a-bb9c-63519090d53d.png)

**Comment by lostmsu** [comment]
The error is quite specific. You have TensorFlow 2.1, and the package requires 1.15

**Comment by AbdalaMask** [comment]
![image](https://user-images.githubusercontent.com/37013638/199317842-adc39b01-0007-4a62-9ee8-e1dd1563305d.png)

**Comment by AbdalaMask** [comment]
![image](https://user-images.githubusercontent.com/37013638/199318364-540ba9ed-b5c6-4c4b-9c2b-679115cad3f5.png)
It is possible to update the project to the latest version of TensorFlow 2.1

**Comment by AbdalaMask** [comment]
losttech.tensorflow.2.5.0-rc1

**Comment by AbdalaMask** [comment]
losttech.tensorflow.2.5.0-rc1 working to TensorFlow 2.1

**Comment by AbdalaMask** [comment]
![image](https://user-images.githubusercontent.com/37013638/199323412-86f98164-cdad-4bf9-ac19-ff19026cfd6b.png)

**Comment by lostmsu** [comment]
You should install matching TensorFlow version. E.g. 1.15 for 1.15 and 2.5 for 2.5
